version: "3.0"
services:
  web:
    build: ./webapp
    environment:
      - VUE_APP_BACKEND_URL: http://back:3000
    depends_on:
      - back
  back:
    build: ./back
    environment:
      - PORT: 3000
