version: "2.1"
services:
  web:
    build:
      context: ./webapp
      args:
        VUE_APP_BACKEND_URL: http://192.168.99.100:3000
    restart: always
    ports:
      - "80:80"
    depends_on:
      - back
  back:
    build: ./back
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DB_NAME=vitta
      - PORT=3000
      - USE_JSON_SERVER=false
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:8.0.18
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=vitta
      - MYSQL_ROOT_PASSWORD=example
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
